# Generated by Django 2.1.7 on 2019-04-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSchedule', '0002_tprioritydimension_tpriorityselect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tprioritydimension',
            options={'ordering': ['-weight_ratio']},
        ),
    ]
