# Generated by Django 2.1.7 on 2019-03-23 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TEventTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outline', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('created_by_id', models.ForeignKey(on_delete=None, related_name='t_event_tag_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by_id', models.ForeignKey(on_delete=None, related_name='t_event_tag_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_event_tag',
            },
        ),
        migrations.CreateModel(
            name='TEventType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('outline', models.CharField(max_length=32)),
                ('level', models.IntegerField(choices=[(1, '一级事件'), (2, '二级事件'), (3, '三级事件')])),
                ('parent_event_id', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField()),
                ('updated_datetime', models.DateTimeField()),
                ('created_by_id', models.ForeignKey(on_delete=None, related_name='t_event_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by_id', models.ForeignKey(on_delete=None, related_name='t_event_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_event_type',
            },
        ),
    ]
