# Generated by Django 2.1.7 on 2019-03-23 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', '男性-Male'), ('F', '女性-Female')], max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, default='无', max_length=100, verbose_name='地址')),
                ('telephone', models.CharField(blank=True, default='无', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_profile',
            },
        ),
    ]
